author: "Vincent Labreche <vlabreche@equiis.com>"
category: "auth"
summary: "Authentication via a JWT Token"
home: "https://github.com/equiis/ejabberd-auth-jwt"
url: "git@github.com:Equiis/ejabberd-auth-jwt.git"